name: Go CI 

on:
  push:
    branches: [ main ]
  pull_requests:
    branches: [ main ]

jons:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/chekout@v4

      - name: Setup Go
        uses: actions/setup Go
        with:
          go-version: '1.22'

      - name: Download dependencies
        run: go mod download 

      - name: Run test
        run: go test -race -cover ./... 

      - name: Run go vet
        run: go vet ./...
